# Generated by Django 3.1.7 on 2021-08-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('dID', models.AutoField(primary_key=True, serialize=False)),
                ('dName', models.CharField(max_length=20)),
                ('dPwd', models.CharField(max_length=25)),
                ('dInfo', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('mID', models.AutoField(primary_key=True, serialize=False)),
                ('mName', models.CharField(max_length=20)),
                ('mPwd', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pName', models.CharField(max_length=30)),
                ('pID', models.AutoField(primary_key=True, serialize=False)),
                ('pPwd', models.CharField(max_length=25)),
                ('pPhone', models.CharField(max_length=11)),
                ('pAddr', models.CharField(max_length=30)),
                ('pEmail', models.CharField(max_length=20)),
                ('pTall', models.DecimalField(decimal_places=3, max_digits=3)),
                ('pWeight', models.DecimalField(decimal_places=3, max_digits=3)),
                ('pAge', models.IntegerField()),
                ('pSex', models.CharField(max_length=1)),
                ('pAller', models.TextField(max_length=200)),
                ('pCharacter', models.BooleanField(default=False)),
            ],
        ),
    ]
