# Generated by Django 3.1.7 on 2021-08-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=30)),
                ('img', models.FileField(blank=True, null=True, upload_to='test', verbose_name='商品图片')),
            ],
        ),
    ]
