# Generated by Django 3.2.8 on 2022-04-13 02:54

from django.db import migrations, models
import eyes.storage


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210923_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(db_column='photo_ID', primary_key=True, serialize=False)),
                ('photo_realname', models.CharField(max_length=255)),
                ('photo_img', models.FileField(max_length=255, storage=eyes.storage.ImageStorage(), upload_to='test')),
                ('photo_promap', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_savename', models.CharField(max_length=255)),
                ('photo_upload', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_photo',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Pho',
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': False},
        ),
    ]
